# fly.preview.toml - configuration for preview environments
app = 'rss-reader-highlight-preview'
primary_region = 'ewr'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DATABASE_PATH = "data/rss.db"  # Use local path for ephemeral preview

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# No volume mounts for preview - use ephemeral database

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256