name: Deploy Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: ewr

jobs:
  preview_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy PR preview to Fly.io
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          config: fly.preview.toml